name: study
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # used for comparing objects
  equatable: ^2.0.3
  # Used for state mgt
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  uuid: ^3.0.6
  get_it: ^7.2.0
  logger: ^1.1.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
