name: study
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # used for comparing objects
  equatable: ^2.0.3
  # Used for state mgt
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  uuid: ^3.0.6
  get_it: ^7.2.0
  logger: ^1.1.0
  dio: ^4.0.6
  lottie: ^1.3.0
  json_annotation: ^4.4.0
  rxdart: ^0.27.3
  speech_to_text: ^5.4.3
  flutter_spinkit: ^5.1.0
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.6
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/sounds/
